global using Newtonsoft.Json;
global using System;
global using System.IO;
global using System.Text;
global using Microsoft.Extensions.Hosting;
global using ShopBuddy.Services.Interfaces;
global using ShopBuddy.Data.Configuration;
global using System.Security.Cryptography;
global using System.ComponentModel.DataAnnotations;
